require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const { db, ensureAdmin } = require('./db');

ensureAdmin();

const menuItems = [
  {
    name: 'Lõunakombo',
    category: 'Eripakkumised',
    description: 'Ramen + eelroog + jook — täiuslik lõunapaus. Valik rameni ja eelrooga, juurde värsked joogid.',
    price: 17,
    spiciness: 0,
    ingredients: 'Ramen, eelroog, jook',
    allergens: 'Gluteen, sojauba',
    image: '/media/combos/lunch_combo.webp',
    is_new: 0,
  },
  {
    name: 'Paarikombo',
    category: 'Eripakkumised',
    description: 'Kaks ramenikaussi + jagamisplaat + kaks jooki. Romantiline õhtu algab siit.',
    price: 42,
    spiciness: 0,
    ingredients: '2x ramen, jagamisplaat, 2x jook',
    allergens: 'Gluteen, sojauba, muna',
    image: '/media/combos/couple_combo.webp',
    is_new: 0,
  },
  {
    name: 'Ramen & Õlu',
    category: 'Eripakkumised',
    description: 'Sinu lemmik ramen koos käsitöö- või Jaapani õllega. Klassikaline kombinatsioon.',
    price: 23,
    spiciness: 0,
    ingredients: 'Ramen, käsitööõlu',
    allergens: 'Gluteen, sojauba',
    image: '/media/combos/beer_combo.webp',
    is_new: 0,
  },
  {
    name: 'Vegan Kombo',
    category: 'Eripakkumised',
    description: '100% taimne — vegan ramen + taimne eelroog + taimne jook.',
    price: 25,
    spiciness: 1,
    ingredients: 'Vegan ramen, taimne eelroog, taimne jook',
    allergens: 'Sojauba',
    image: '/media/combos/vegan_combo.webp',
    is_new: 0,
  },
  {
    name: 'Laua Jagamisplaat',
    category: 'Eripakkumised',
    description: 'Suurele seltskonnale — kõik eelroad, mitu ramenikaussi, joogid. Täisõhtu kogemus.',
    price: 99,
    spiciness: 0,
    ingredients: 'Kõik eelroad, mitu ramenikaussi, joogid',
    allergens: 'Gluteen, sojauba, muna, kala, koorikloomad',
    image: '/media/combos/plate_combo.webp',
    is_new: 0,
  },
  {
    name: 'Spicy Challenge',
    category: 'Eripakkumised',
    description: 'Kas julged? Kõige kuumem ramen pluss tulise kastmega karaage. Ainult tugevatele.',
    price: 24,
    spiciness: 3,
    ingredients: 'Ultra-vürtsikas ramen, tulise kastmega karaage',
    allergens: 'Gluteen, sojauba, muna',
    image: '/media/combos/spicy_combo.webp',
    is_new: 0,
  },
  {
    name: 'Gyoza',
    category: 'Eelroad & Suupisted',
    description: 'Krõbedad praetud pelmeenid. Seest mahlane, väljast kuldpruun krõbe koor. Serveeritakse ponzu kastmega.',
    price: 7,
    spiciness: 0,
    ingredients: 'Sealiha, kapsas, küüslauk, ingver, sojakaste, seesamiõli',
    allergens: 'Gluteen, sojauba',
    image: '/media/food/gyoza.webp',
    is_new: 0,
  },
  {
    name: 'Karaage',
    category: 'Eelroad & Suupisted',
    description: 'Jaapani stiilis praetud kana — krõbe ja mahlane. Serveeritakse sidruni ja Kewpie mayoga.',
    price: 8,
    spiciness: 0,
    ingredients: 'Kana reietükid, sojakaste, sake, ingver, küüslauk, tärklis',
    allergens: 'Gluteen, sojauba, muna',
    image: '/media/food/karaage.webp',
    is_new: 0,
  },
  {
    name: 'Edamame Chilli Võiga',
    category: 'Eelroad & Suupisted',
    description: 'Aurutatud sojaoad koos suitsuse chilli-võiga. Lihtne aga sõltuvust tekitav suupiste.',
    price: 5,
    spiciness: 1,
    ingredients: 'Edamame, või, chiliflokkid, meresoola',
    allergens: 'Sojauba, piim',
    image: '/media/food/edamame.webp',
    is_new: 0,
  },
  {
    name: 'Tonkotsu',
    category: 'Ramen',
    description: 'Kreemjas seapuljong, mis on keedetud 18 tundi. Koos chashu sealiha, ajitsuke munaga ja nori\'ga.',
    price: 16,
    spiciness: 0,
    ingredients: 'Seapuljong, ramenunuudlid, chashu sealiha, ajitsuke muna, nori, bambusevõrsed, roheline sibul',
    allergens: 'Gluteen, muna, sojauba',
    image: '/media/food/tonkotsu.webp',
    is_new: 0,
  },
  {
    name: 'Shio',
    category: 'Ramen',
    description: 'Selge ja õrn meresoola puljong. Kana ja mereandide delikaatne maailm.',
    price: 15,
    spiciness: 0,
    ingredients: 'Kanapuljong, ramenunuudlid, chashu kana, muna, nori, yuzu',
    allergens: 'Gluteen, muna, sojauba, kala',
    image: '/media/food/shio.webp',
    is_new: 0,
  },
  {
    name: 'Miso',
    category: 'Ramen',
    description: 'Rikkalik fermenteeritud sojauba puljong. Sügav umami, koos praetud küüslauguvõiga.',
    price: 15,
    spiciness: 1,
    ingredients: 'Miso puljong, ramenunuudlid, chashu sealiha, muna, mais, või, nori',
    allergens: 'Gluteen, muna, sojauba, piim',
    image: '/media/food/miso.webp',
    is_new: 0,
  },
  {
    name: 'Spicy Tantanmen',
    category: 'Ramen',
    description: 'Hiina inspireeritud tan tan ramen — seesamipohjaline puljong, hakklihakaste ja chili õliga.',
    price: 16,
    spiciness: 2,
    ingredients: 'Seesamipuljong, ramenunuudlid, sealiha hakkliha, pak choi, chili õli, rohelised sibulad',
    allergens: 'Gluteen, sojauba, seesam',
    image: '/media/food/tantanmen.webp',
    is_new: 1,
  },
  {
    name: 'Shoyu Tori',
    category: 'Ramen',
    description: 'Klassikaline sojakaste-baasil puljong. Kergem ja aromaatsem, Tokyost inspireeritud.',
    price: 14,
    spiciness: 0,
    ingredients: 'Shoyu puljong, ramenunuudlid, chashu kana, muna, menma, nori',
    allergens: 'Gluteen, muna, sojauba',
    image: '/media/food/shoyu.webp',
    is_new: 0,
  },
  {
    name: 'Vegan Shitake Dashi',
    category: 'Ramen',
    description: '100% taimne ramen shiitake dashi puljongis. Rikas umami ilma loomsete toodeteta.',
    price: 13,
    spiciness: 0,
    ingredients: 'Shiitake puljong, ramenunuudlid, tofu, mais, bambusevõrsed, nori, rohelised sibulad',
    allergens: 'Gluteen, sojauba',
    image: '/media/food/shiitake.webp',
    is_new: 1,
  },
  {
    name: 'Takoyaki',
    category: 'Kõrvale',
    description: 'Jaapani tintkalmarikuulid — krõbedad väljast, pehmed seest. Kaetud takoyaki kastme, mayo ja bonito helvestega.',
    price: 9,
    spiciness: 0,
    ingredients: 'Jahu, munad, tintkalmaritükid, takoyaki kaste, Kewpie mayo, bonito helved, ao nori',
    allergens: 'Gluteen, muna, kala, koorikloomad',
    image: '/media/food/takoyaki.webp',
    is_new: 0,
  },
  {
    name: 'Kasutera Chashu Riisinõu',
    category: 'Kõrvale',
    description: 'Aurutatud jasmiinriis koos aeglaselt hautatud chashu sealiha ja muna ning teriyaki kastmega.',
    price: 10,
    spiciness: 0,
    ingredients: 'Jasmiinriis, chashu sealiha, ajitsuke muna, teriyaki kaste, sesam, rohelised sibulad',
    allergens: 'Gluteen, muna, sojauba, seesam',
    image: '/media/food/kasutera.webp',
    is_new: 0,
  },
  {
    name: 'Mochi Jäätis',
    category: 'Magustoit',
    description: 'Kleepuv riisitaina ümbrik täidetud premium jäätisega. Maitsed: matcha, mango, mustikas.',
    price: 6,
    spiciness: 0,
    ingredients: 'Glutinoosne riisijahu, suhkur, tärklisesirup, jäätis (matcha/mango/mustikas)',
    allergens: 'Piim',
    image: '/media/food/mochi.webp',
    is_new: 0,
  },
  {
    name: 'Hojicha Crème Brûlée',
    category: 'Magustoit',
    description: 'Röstitud tee kreemiga täidetud klassikaline prantsuse magustoit Jaapani hojichaga.',
    price: 7,
    spiciness: 0,
    ingredients: 'Hojicha tee, koor, munakollased, suhkur',
    allergens: 'Muna, piim',
    image: '/media/food/hojicha.webp',
    is_new: 1,
  },
  {
    name: 'Yuzu Lemonaad',
    category: 'Joogid',
    description: 'Värskendav yuzu tsitrusest käsitöö lemonaad, kergelt vahune. Suvine ja hele.',
    price: 5,
    spiciness: 0,
    ingredients: 'Yuzu mahl, suhkrusiirup, sparkling vesi, jää',
    allergens: '',
    image: '/media/drinks/yuzu.webp',
    is_new: 0,
  },
  {
    name: 'Calpico Soda',
    category: 'Joogid',
    description: 'Jaapani piimapõhine gaseeritud jook — magus, hapukas, kergelt kreemjas.',
    price: 4,
    spiciness: 0,
    ingredients: 'Vesi, suhkur, piimakonsentraat, sidrunhape',
    allergens: 'Piim',
    image: '/media/drinks/calpico.webp',
    is_new: 0,
  },
  {
    name: 'Mugicha',
    category: 'Joogid',
    description: 'Jaapani traditsiooniline odratee — pähkline, röstitud maitse. Serveeritakse külmalt.',
    price: 3,
    spiciness: 0,
    ingredients: 'Röstitud oder, vesi',
    allergens: 'Gluteen',
    image: '/media/drinks/mugicha.webp',
    is_new: 0,
  },
  {
    name: 'Ramune',
    category: 'Joogid',
    description: 'Ikooniline Jaapani gaseeritud limonaad klaaskuuliga pudelis. Maitsed: originaal, mango, maasikas.',
    price: 4,
    spiciness: 0,
    ingredients: 'Vesi, suhkur, sidrunhape, looduslikud lõhna-ained',
    allergens: '',
    image: '/media/drinks/ramune.webp',
    is_new: 0,
  },
];

const insert = db.prepare(`
  INSERT INTO menu_items (name, category, description, price, spiciness, ingredients, allergens, image, is_new)
  VALUES (@name, @category, @description, @price, @spiciness, @ingredients, @allergens, @image, @is_new)
`);

const insertMany = db.transaction((items) => {
  for (const item of items) insert.run(item);
});

const existing = db.prepare('SELECT COUNT(*) as count FROM menu_items').get();
if (existing.count === 0) {
  insertMany(menuItems);
  console.log(`${menuItems.length} menüükirjet lisatud andmebaasi.`);
} else {
  console.log(`Andmebaasis on juba ${existing.count} menüükirjet — seed vahele jäetud.`);
}

console.log('Seedimine lõpetatud.');
process.exit(0);
